# Generated by Django 2.1.5 on 2019-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('aadhar_number', models.BigIntegerField(max_length=12)),
                ('pan_card', models.BigIntegerField(max_length=15)),
                ('date_of_join', models.DateField(auto_now_add=True)),
                ('dept_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
