# Generated by Django 2.1.5 on 2019-03-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='SID',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_join',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pan_card',
        ),
    ]
