# Generated by Django 2.1.5 on 2019-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20190311_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
