# Generated by Django 2.1.5 on 2019-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20190314_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=100)),
                ('estd', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
