# Generated by Django 2.1.5 on 2019-04-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_register4'),
    ]

    operations = [
        migrations.CreateModel(
            name='personaldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dateofbirth', models.DateTimeField()),
                ('emailid', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=10)),
                ('alternatemobile', models.IntegerField(max_length=10)),
                ('aadharnumber', models.IntegerField(max_length=16)),
                ('pancardnumber', models.IntegerField(max_length=20)),
                ('bloodgroup', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('dateofjoining', models.DateTimeField(max_length=200)),
                ('departmentname', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
    ]
