# Generated by Django 2.1.5 on 2019-04-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_personaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awardsdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardname', models.CharField(max_length=600)),
                ('awardinstitution', models.CharField(max_length=600)),
                ('date', models.DateField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='bachelorsdegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreename', models.CharField(max_length=400)),
                ('collegename', models.CharField(max_length=400)),
                ('University', models.CharField(max_length=400)),
                ('yearofpassing', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=600)),
                ('percentage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experiencedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutename', models.CharField(max_length=600)),
                ('joiningdate', models.DateField()),
                ('designation', models.CharField(max_length=600)),
                ('hikename', models.CharField(max_length=600)),
                ('scale', models.CharField(max_length=600)),
                ('enddate', models.DateField()),
                ('address', models.CharField(max_length=600)),
                ('state', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='grantsapplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('projectname', models.CharField(max_length=600)),
                ('agency', models.CharField(max_length=600)),
                ('grantamount', models.IntegerField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='grantsfetched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=600)),
                ('grantissuedby', models.CharField(max_length=600)),
                ('grantedamount', models.IntegerField(max_length=600)),
                ('grantdate', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='mastersdegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreename', models.CharField(max_length=400)),
                ('collegename', models.CharField(max_length=400)),
                ('University', models.CharField(max_length=400)),
                ('yearofpassing', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=600)),
                ('percentage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patentsdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=600)),
                ('dateofprovisional', models.DateField()),
                ('dateofcomplete', models.DateField()),
                ('dateofpublication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='phddegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreename', models.CharField(max_length=400)),
                ('collegename', models.CharField(max_length=400)),
                ('University', models.CharField(max_length=400)),
                ('specification', models.CharField(max_length=500)),
                ('yearofpassing', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=600)),
                ('percentage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='publicationdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleofpublication', models.CharField(max_length=600)),
                ('authorname', models.CharField(max_length=600)),
                ('year', models.DateField()),
                ('titleofpaper', models.CharField(max_length=600)),
                ('volume', models.CharField(max_length=600)),
                ('pagenumbers', models.CharField(max_length=600)),
                ('impact', models.CharField(max_length=600)),
                ('reviewer', models.CharField(max_length=600)),
                ('journalname', models.CharField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dateofbirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dateofjoining',
            field=models.DateField(max_length=200),
        ),
    ]
