# Generated by Django 2.1.5 on 2019-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20190404_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshopdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentationlevel', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=400)),
                ('sourceoffunding', models.CharField(max_length=400)),
                ('paper', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=900)),
                ('country', models.CharField(max_length=900)),
                ('state', models.CharField(max_length=400)),
                ('startdate', models.DateField()),
                ('date', models.DateField()),
                ('hostorganization', models.CharField(max_length=900)),
                ('eventname', models.CharField(max_length=900)),
                ('area', models.CharField(max_length=900)),
                ('resourceperson', models.CharField(max_length=600)),
                ('place', models.CharField(max_length=900)),
                ('numberofparticipants', models.IntegerField(max_length=400)),
                ('briefdescription', models.CharField(max_length=990)),
                ('amountfaculty', models.IntegerField()),
                ('modeofpayment', models.CharField(max_length=600)),
                ('amountuniversity', models.CharField(max_length=900)),
            ],
        ),
    ]
