# Generated by Django 2.1.5 on 2019-04-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_workshopdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdetails',
            name='numberofparticipants',
            field=models.IntegerField(),
        ),
    ]
