# Generated by Django 2.1.5 on 2019-04-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20190405_2359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workshop',
        ),
    ]
