# Generated by Django 2.1.5 on 2019-04-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_delete_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='patentsdetails4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=600)),
                ('holder', models.CharField(max_length=600)),
                ('datesubmitprovisional', models.DateField()),
                ('datesubmitcomplete', models.DateField()),
                ('datepublication', models.DateField()),
                ('remarks', models.CharField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='patentsdetails',
        ),
    ]
