# Generated by Django 2.1.5 on 2019-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20190406_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awardsdetails4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardname', models.CharField(max_length=600)),
                ('awardinstitution', models.CharField(max_length=600)),
                ('date', models.DateField(max_length=600)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='bankdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=900)),
                ('accountnumber', models.IntegerField()),
                ('branchname', models.CharField(max_length=900)),
                ('ifsccode', models.CharField(max_length=900)),
                ('city', models.CharField(max_length=900)),
                ('state', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='grantsapplied4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('projectname', models.CharField(max_length=600)),
                ('agency', models.CharField(max_length=600)),
                ('grantamount', models.IntegerField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='grantsfetched4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=600)),
                ('grantissuedby', models.CharField(max_length=600)),
                ('grantedamount', models.IntegerField(max_length=600)),
                ('grantdate', models.DateField()),
                ('coauthors', models.CharField(max_length=900)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=900)),
            ],
        ),
        migrations.DeleteModel(
            name='Awardsdetails',
        ),
        migrations.DeleteModel(
            name='grantsapplied',
        ),
        migrations.DeleteModel(
            name='grantsfetched',
        ),
    ]
