# Generated by Django 2.1.5 on 2019-04-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20190406_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantsapplied4',
            name='grantamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grantsfetched4',
            name='grantedamount',
            field=models.IntegerField(),
        ),
    ]
