# Generated by Django 2.1.5 on 2019-04-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0016_auto_20190406_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('code', models.CharField(max_length=500)),
                ('credit', models.IntegerField()),
                ('created', models.DateField()),
                ('department', models.CharField(max_length=600)),
                ('facultycourse', models.CharField(max_length=600)),
                ('coursedescription', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='facultydetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=700)),
                ('mobile', models.IntegerField()),
                ('facultycourse', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=700)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
