# Generated by Django 2.1.5 on 2019-04-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_coursedetails_facultydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='facultycourse',
        ),
    ]
