# Generated by Django 2.1.5 on 2019-04-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_remove_coursedetails_facultycourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coursedetails',
        ),
    ]
