# Generated by Django 2.1.5 on 2019-04-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_coursedetails4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultydetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='facultydetails',
        ),
    ]
