# Generated by Django 2.1.5 on 2019-04-07 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0021_auto_20190407_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultydetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=700)),
                ('mobile', models.IntegerField()),
                ('joining', models.DateField()),
                ('facultycourse', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=700)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
