# Generated by Django 2.1.5 on 2019-04-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_personaldetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='user',
        ),
    ]
