# Generated by Django 2.1.5 on 2019-04-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_remove_personaldetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
    ]
