# Generated by Django 2.1.5 on 2019-04-30 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0026_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('emailid', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('alternatemobile', models.IntegerField()),
                ('aadharnumber', models.IntegerField()),
                ('pancardnumber', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('dateofjoining', models.DateField(max_length=200)),
                ('departmentname', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='personaldetails',
        ),
    ]
