# Generated by Django 2.1.5 on 2019-04-30 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0030_auto_20190430_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutename', models.CharField(max_length=600)),
                ('joiningdate', models.DateField()),
                ('designation', models.CharField(max_length=600)),
                ('hikename', models.CharField(max_length=600)),
                ('scale', models.CharField(max_length=600)),
                ('enddate', models.DateField()),
                ('address', models.CharField(max_length=600)),
                ('state', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='experiencedetails',
        ),
    ]
