# Generated by Django 2.1.5 on 2019-04-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0035_auto_20190430_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardname', models.CharField(max_length=600)),
                ('awardinstitution', models.CharField(max_length=600)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=900)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Awardsdetails4',
        ),
    ]
