# Generated by Django 2.1.5 on 2019-04-30 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0036_auto_20190430_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentationlevel', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=400)),
                ('sourceoffunding', models.CharField(max_length=400)),
                ('paper', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=900)),
                ('country', models.CharField(max_length=900)),
                ('state', models.CharField(max_length=400)),
                ('startdate', models.DateField()),
                ('date', models.DateField()),
                ('hostorganization', models.CharField(max_length=900)),
                ('eventname', models.CharField(max_length=900)),
                ('area', models.CharField(max_length=900)),
                ('resourceperson', models.CharField(max_length=600)),
                ('place', models.CharField(max_length=900)),
                ('numberofparticipants', models.IntegerField()),
                ('briefdescription', models.CharField(max_length=990)),
                ('amountfaculty', models.IntegerField()),
                ('modeofpayment', models.CharField(max_length=600)),
                ('amountuniversity', models.CharField(max_length=900)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='workshopdetails',
        ),
    ]
