# Generated by Django 2.1.5 on 2019-04-30 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0037_auto_20190430_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=900)),
                ('accountnumber', models.IntegerField()),
                ('branchname', models.CharField(max_length=900)),
                ('ifsccode', models.CharField(max_length=900)),
                ('city', models.CharField(max_length=900)),
                ('state', models.CharField(max_length=900)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='bankdetails',
        ),
    ]
