# Generated by Django 2.1.5 on 2019-04-30 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0038_auto_20190430_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('code', models.CharField(max_length=500)),
                ('credit', models.IntegerField()),
                ('created', models.DateField()),
                ('department', models.CharField(max_length=600)),
                ('semester', models.IntegerField()),
                ('coursedescription', models.CharField(max_length=600)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='coursedetails4',
        ),
    ]
